name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: curl GET
        run: curl -s https://jsonplaceholder.typicode.com/posts/1
        
      - name: curl POST
        run: "curl -s -d \"{'title':'CURL Post', 'body': 'Great CURL Post'}\" -H \"Content-Type: application/json\" -X POST https://jsonplaceholder.typicode.com/posts"
      
      - name: use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: fetch GET script
        run: node fetch-get.js

      - name: fetch POST script
        run: node fetch-post.js

      # - name: curl GET Output
      #   id: curlget
      #   run: | 
      #     RESPONSE=$(curl -s https://jsonplaceholder.typicode.com/posts/1)
      #     printf "%s" "FOO=$RESPONSE" >> $GITHUB_OUTPUT

      - name: foo
        id: bar
        run: |
          echo 'RESPONSE<<EOF' >> $GITHUB_OUTPUT
          curl -s https://jsonplaceholder.typicode.com/posts/1 >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: do stuff with the response from curl
        run: printf "%s" "${{ steps.bar.outputs.FOO }}" | jq .title
